server:
   port: 8050
spring:
  data:
    mongodb:
      database: bezkoderdb
      host: localhost
      port: 27017
  application:
    name: AUTH-SERVICE
      
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000

eureka:
 client:
   register-with-eureka: true
   fetch-registry: true
   service-url.default-zone: http://localhost:8761/eureka
   instance.hostname: localhsot